---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-oh-my-zsh-fedora-33
    image: fedora:33

provisioner:
  name: ansible

verifier:
  name: testinfra
