---
name: CI
'on':
  pull_request:
  push:
    branches:
jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker testinfra yamllint ansible-lint
      - name: Run Molecule tests.
        run: ./molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
